### ISSUE TITLE
Error not loaded 'define-properties'

### ISSUE THREAD

**Issue by jeremy-holt** [es-shims/Array.prototype.filter#2]
I submitted this bug report on the bootstrap project as well

I'm using aurelia v1.0, bootstrap 5.0.1
I ran yarn upgrade and am now getting an error not loaded: define-properties.
I've been able to track the error down to array.prototype.filter which is installed only by bootstrap 5.0.1
I'm guessing that the error is in the first line of index.js
```
'use strict';

var define = require('define-properties');
var RequireObjectCoercible = require('es-abstract/2020/RequireObjectCoercible');
var callBound = require('call-bind/callBound');

var implementation = require('./implementation');
var getPolyfill = require('./polyfill');
var polyfill = getPolyfill();
var shim = require('./shim');

var $slice = callBound('Array.prototype.slice');

// eslint-disable-next-line no-unused-vars
var bound = function filter(array, callbackfn) {
	RequireObjectCoercible(array);
	return polyfill.apply(array, $slice(arguments, 1));
};
define(bound, {
	getPolyfill: getPolyfill,
	implementation: implementation,
	shim: shim
});

module.exports = bound;
```
I have run npm define-properties but to no avail.

I have also cloned the array.prototype.filter project and can't even get it to run the tests

The project seems to have been updated a few days ago, but I can't find the previous version.

I should add that my project was running perfectly until this morning.

Window 10 pro 10.0.19043
Microsoft Edge Version 90.0.818.62

**Comment by ljharb** [comment]
I'm not familiar with aurelia.

bootstrap 5 does not directly depend on this package.

The version with `define-properties` is new, in v1.0.0 (a major version, which`yarn upgrade` would not update to), and the package correctly defines its dependencies.

When you clone the project, `npm install && npm test` doesn't work for you? What node version are you on?

**Comment by jeremy-holt** [comment]
Thanks for getting back to me on this.
Bootstrap 5.0.1 does use array.prototype.filter (or at least one of its dependencies does)
I'm on node 14.17.0

I managed to get bootstrap working again by downgrading both array.prototype.filter and available-types-arrays.

The error I see is
![image](https://user-images.githubusercontent.com/2135027/119172244-3b037180-ba55-11eb-9883-ffb7cd54558c.png)

**Comment by ljharb** [comment]
Try `npm run tests-only`, evalmd probably doesn’t work on windows.

As for the package, can you run `yarn why array.prototype.filter` in your package? Also, can you run `yarn` to be sure everything’s installed?

**Comment by jeremy-holt** [comment]
I had run npm install. On running yarn install `npm run tests-only`, the tests ran fine.

`yarn why array.prototype.filter` gave me this. Much to my surprise it's used by `aurelia-cli` which is strange because none of my other projects show `array.prototype.filter` being used, and if I remove `bootstrap` the dependency on `array.prototype.filter` disappears????

![image](https://user-images.githubusercontent.com/2135027/119215310-71280c00-babc-11eb-9397-a50137cb3881.png)

I'll ask about this at https://discourse.aurelia.io/t/for-anyone-seeing-problems-with-bootstrap-5-0-1/4224

**Comment by ljharb** [comment]
Seems unrelated to this package. Happy to help if more info surfaces.
